Metrics/BlockLength:
  CountComments: false
  Max: 5
  Exclude:
    - 'config/routes.rb'
  IgnoredMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group
    - included
    - factory
    - define
    - trait
    - perform_enqueued_jobs
    - travel_to
    - use_cassette

Style/FrozenStringLiteralComment:
  Description: >-
    Add the frozen_string_literal comment to the top of files
    to help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false
